apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
        - name: eureka-service
          image: bigbenj4/eureka-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          resources:
            limits:
              memory: "384Mi"
              cpu: "300m"
            requests:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: URL_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: URL_CONFIG
            - name: EUREKA_HOST
              value: "eureka-service"
            - name: EUREKA_PORT
              value: "8761"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  selector:
    app: eureka-service
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP
