apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: bigbenj4/gateway-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "400m"
            requests:
              memory: "384Mi"
              cpu: "200m"
          env:
            - name: URL_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: URL_CONFIG
            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: EUREKA_HOST
            - name: EUREKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: EUREKA_PORT
            # URL externa de Keycloak (accesible desde navegador y Gateway)
            - name: KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: KEYCLOAK_EXTERNAL_URL
            # IMPORTANTE: Ambas URIs deben ser la URL EXTERNA para que el issuer coincida
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: KEYCLOAK_JWK_SET_URI
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: KEYCLOAK_ISSUER_URI
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort
