apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loans-service
  template:
    metadata:
      labels:
        app: loans-service
    spec:
      containers:
        - name: loans-service
          image: bigbenj4/loans-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: URL_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: URL_CONFIG
            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: EUREKA_HOST
            - name: EUREKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: EUREKA_PORT
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: loans-service
spec:
  selector:
    app: loans-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
