apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reports-service
  template:
    metadata:
      labels:
        app: reports-service
    spec:
      containers:
        - name: reports-service
          image: bigbenj4/reports-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "384Mi"
              cpu: "300m"
            requests:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: URL_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: URL_CONFIG
            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: EUREKA_HOST
            - name: EUREKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: EUREKA_PORT
            - name: URL_DB
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: URL_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: KEYCLOAK_URL
              value: "http://keycloak-service:8080"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: "http://keycloak-service:8080/realms/tingeso/protocol/openid-connect/certs"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://192.168.39.241:31000/realms/tingeso"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: reports-service
spec:
  selector:
    app: reports-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
