pipeline {
    agent any
    environment {
        DOCKERHUB_USERNAME = 'bigbenj4' 
        BACKEND_IMAGE_NAME = "${env.DOCKERHUB_USERNAME}/toolrent-backend"
        FRONTEND_IMAGE_NAME = "${env.DOCKERHUB_USERNAME}/toolrent-frontend"
        IMAGE_TAG = "${env.BUILD_ID}"
        DOCKERHUB_CREDENTIALS = 'dockerhub-credentials-id' 
        SSH_CREDENTIALS = 'ssh-server-credentials-id'
        TARGET_USER = 'benjaminhernandez' 
        TARGET_HOST = '127.0.0.1'
        DEPLOY_DIR = 'deployment_toolrent'
        DOCKER_CONTEXT = "default"
    }

    stages {
        stage('Build & Push Backend') {
            steps {
                script {
                    echo "--- Construyendo Backend para: ${env.BACKEND_IMAGE_NAME}:${env.IMAGE_TAG} ---"
                    def backendImage = docker.build("${env.BACKEND_IMAGE_NAME}:${env.IMAGE_TAG}", "-f Backend-ToolRent/Dockerfile Backend-ToolRent")
                    docker.withRegistry("https://index.docker.io/v1/", "${env.DOCKERHUB_CREDENTIALS}") {
                        backendImage.push()
                        backendImage.push("latest")
                    }
                }
            }
        }

        stage('Build & Push Frontend') {
            steps {
                script {
                    echo "--- Construyendo Frontend para: ${env.FRONTEND_IMAGE_NAME}:${env.IMAGE_TAG} ---"
                    def frontendImage = docker.build("${env.FRONTEND_IMAGE_NAME}:${env.IMAGE_TAG}", "-f Frontend-ToolRent/Dockerfile Frontend-ToolRent")
                    docker.withRegistry("https://index.docker.io/v1/", "${env.DOCKERHUB_CREDENTIALS}") {
                        frontendImage.push()
                        frontendImage.push("latest")
                    }
                }
            }
        }

        stage('Deploy to Production') {
            steps {
                sshagent([env.SSH_CREDENTIALS]) {
                    withCredentials([
                        string(credentialsId: 'DB_PASS', variable: 'DB_PASS'),
                        string(credentialsId: 'KEYCLOAK_ADMIN_PASS', variable: 'KEYCLOAK_ADMIN_PASS')
                    ]) {
                        script {
                            sh "ssh -o StrictHostKeyChecking=no ${env.TARGET_USER}@${env.TARGET_HOST} 'mkdir -p ${env.DEPLOY_DIR}/config/keycloak-realm'"
                            
                            sh "scp Deployment/docker-compose.prod.yml ${env.TARGET_USER}@${env.TARGET_HOST}:${env.DEPLOY_DIR}/docker-compose.yml"
                            sh "scp Backend-ToolRent/nginx.conf ${env.TARGET_USER}@${env.TARGET_HOST}:${env.DEPLOY_DIR}/config/nginx.conf"
                            sh "scp -r Backend-ToolRent/keycloak-realm/* ${env.TARGET_USER}@${env.TARGET_HOST}:${env.DEPLOY_DIR}/config/keycloak-realm/"

                            def env_vars = """
                                export BACKEND_IMAGE_NAME=${env.BACKEND_IMAGE_NAME}
                                export FRONTEND_IMAGE_NAME=${env.FRONTEND_IMAGE_NAME}
                                export DB_NAME=toolrentdb
                                export DB_USER=admin
                                export DB_PASS=${DB_PASS}
                                export KEYCLOAK_ADMIN_USER=admin
                                export KEYCLOAK_ADMIN_PASS=${KEYCLOAK_ADMIN_PASS}
                                export DOMAIN_NAME=${env.TARGET_HOST}
                                export NGINX_CONF_PATH=./config/nginx.conf
                                export KEYCLOAK_REALM_PATH=./config/keycloak-realm
                            """

                            // Ejecutar comandos Docker en remoto
                            sh """
                                ssh -o StrictHostKeyChecking=no ${env.TARGET_USER}@${env.TARGET_HOST} '
                                    cd ${env.DEPLOY_DIR} && \\
                                    ${env_vars} \\
                                    docker compose pull && \\
                                    docker compose down --remove-orphans && \\
                                    docker compose up -d --no-build

                                    echo "--- Esperando a que Keycloak inicie para configurarlo ---"
                                    # wait-for- it
                                    RETRIES=24
                                    COUNT=0

                                    # Bucle: Intenta hacer curl hasta que devuelva estado 200 (OK)
                                    until curl -s -f -o /dev/null "http://localhost:8080/realms/master"; do
                                        if [ \$COUNT -ge \$RETRIES ]; then
                                            echo "❌ Error: Keycloak no inició después de 2 minutos."
                                            exit 1
                                        fi
                                        echo "⏳ Esperando a Keycloak... (intento \$COUNT/\$RETRIES)"
                                        sleep 5
                                        COUNT=\$((COUNT+1))
                                    done

                                    echo "--- Aplicando parches de seguridad al Master Realm ---"
                                    docker exec toolrent-keycloak-prod /opt/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080 --realm master --user admin --password ${KEYCLOAK_ADMIN_PASS}
                                    
                                    # Desactivar SSL del Master
                                    docker exec toolrent-keycloak-prod /opt/keycloak/bin/kcadm.sh update realms/master -s sslRequired=NONE
                                    
                                    # Arreglar CORS para que puedas entrar desde 127.0.0.1
                                    CID=\$(docker exec toolrent-keycloak-prod /opt/keycloak/bin/kcadm.sh get clients -r master -q clientId=security-admin-console --fields id --format csv --noquotes)
                                    docker exec toolrent-keycloak-prod /opt/keycloak/bin/kcadm.sh update clients/\$CID -r master -s "redirectUris=[\\"http://localhost:8080/*\\",\\"http://${env.TARGET_HOST}:8080/*\\"]" -s "webOrigins=[\\"+ \\"]"
                                '
                            """
                        }
                    }
                }
            }
        }
    }
}